openscad -o metric-prusa/bar-clamp.stl source/bar-clamp.scad
openscad -o metric-prusa/bearing-guide.stl source/bearing-guide.scad
openscad -o metric-prusa/belt-clamp-nut-holder.stl source/belt-clamp-nut-holder.scad
openscad -o metric-prusa/belt-clamp.stl source/belt-clamp.scad
openscad -o metric-prusa/coupling.stl source/coupling.scad
openscad -o metric-prusa/endstop-holder.stl source/endstop-holder.scad
openscad -o metric-prusa/frame-vertex.stl -D 'basefoot=false' source/frame-vertex.scad
openscad -o metric-prusa/frame-vertex-foot.stl source/frame-vertex.scad
openscad -o metric-prusa/printable-bushing.stl source/printable-bushing.scad
openscad -o metric-prusa/printable-bushing-lm8uu.stl source/printable-bushing-lm8uu.scad
openscad -o metric-prusa/pulley.stl source/pulley.scad
openscad -o metric-prusa/rod-clamp.stl source/rod-clamp.scad
openscad -o metric-prusa/sanguinololu-holder.stl source/sanguinololu-holder.scad
openscad -o metric-prusa/wade.stl source/wade.scad
openscad -o metric-prusa/wade-big.stl source/wade-big.scad
openscad -o metric-prusa/wade-small.stl source/wade-small.scad
openscad -o metric-prusa/x-carriage.stl source/x-carriage.scad
openscad -o metric-prusa/x-end-idler.stl source/x-end-idler.scad
openscad -o metric-prusa/x-end-motor.stl source/x-end-motor.scad
openscad -o metric-prusa/y-bushing.stl source/y-bushing.scad
openscad -o metric-prusa/ybrac-t.stl source/ybrac-t.scad
openscad -o metric-prusa/z-motor-mount.stl source/z-motor-mount.scad
